# Generated by Django 5.2.8 on 2025-11-30 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('AIRTIME', 'Airtime Topup'), ('DATA', 'Data Bundle'), ('CABLE', 'Cable TV Subscription'), ('ELECTRICITY', 'Electricity Bill'), ('FUNDING', 'Wallet Funding')], max_length=20)),
                ('network', models.CharField(blank=True, choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('GLO', 'Glo'), ('9MOBILE', '9mobile'), ('OTHERS', 'Others')], max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('plan_code', models.CharField(blank=True, help_text='e.g 1GB-MTN-SME', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
